# routes.yaml

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
listar_peliculas:
    path: /listar_peliculas
    controller: 'App\Controller\WebController::listarPeliculas'
agregar_peliculas:
    path: /agregar_peliculas
    controller: 'App\Controller\WebController::agregarPelicula'
filtrar_por_titulo:
    path: /peliculas/filtrar/titulo/{titulo}
    controller: 'App\Controller\WebController::filtrarPorTitulo'
filtrar_por_fecha:
    path: /peliculas/filtrar/fecha/{fecha}
    controller: 'App\Controller\WebController::filtrarPorFecha'
filtrar_por_valoracion_mayor:
    path: /peliculas/filtrar/valoracion/mayor/{valoracion}
    controller: 'App\Controller\WebController::filtrarPorValoracionMayor'
filtrar_por_valoracion_menor:
    path: /peliculas/filtrar/valoracion/menor/{valoracion}
    controller: 'App\Controller\WebController::filtrarPorValoracionMenor'
